### ISSUE TITLE
Implement Pacman endpoint

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-server#14]
I believe this should consist of a standard set of `POST/GET/PUT/DELETE` operations. @CtrlShiftGo, anything else we need for this?

**Comment by jleung51** [comment]
Working on this using the branch *pacman-controller*.

**Comment by CtrlShiftGo** [comment]
Yes, we will need post operations to create new ghosts, pacman. get to retrieve coordinates of above entities. put to update locations, and delete to remove ghosts, pacman.

**Comment by jleung51** [comment]
Resolved in merge request #22
