### ISSUE TITLE
Implement Pac-Dots/Power-Pellets controller

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-server#15]
What should be stored in the server? Locations (coordinate), eaten (true/false)?

We'll need an admin command for enable-all dots to reset the game.

EDIT:

When the Pacman's location is updated to be near an uneaten pacdot or powerdot and the game is active, the dot should be eaten.

**Comment by jleung51** [comment]
I'll work on this after the controllers and repositories are tested more thoroughly.

**Comment by landalex** [comment]
I think it makes sense if the server stores locations of dots/pills, and the client can fetch all locations or set a dot/pill to "eaten" (which, in the case of the power pill, would change the game state to the mode where Pacman can eat ghosts).

**Comment by jleung51** [comment]
Sounds great. Should pacdots be identified through their coordinate location or through an arbitrary ID?

**Comment by landalex** [comment]
I think just returning coordinate location should be fine. We're thinking of helping to add some game logic onto the server side to remove dots/pills when a character gets into close proximity of a dot/pill, and removing it. The client can simply request a list of all dots/pills in the game, and will only receive the ones that haven't been eaten.

**Comment by jleung51** [comment]
It should be easy client-side to check proximity of dots, since only the Pacman can eat any of the dots. I can provide an endpoint to PUT or DELETE a dot when it's consumed.

Sure, we can have one GET request be for all dots and another GET request be for all "active" dots,

**Comment by landalex** [comment]
Putting checks like this on the client side just duplicates code. We can have it in one place (on the server), or on both the iOS and Android side separately. Having it on the server makes it easier to test, change and maintain, since we can change it and the clients won't know a thing.

**Comment by jleung51** [comment]
Fair enough, I'll add a trigger to the Pacman's `PUT /location` endpoint to eat nearby dots.

Since I need to set the dots before the game, I'll need a list of preset dot coordinates.

**Comment by landalex** [comment]
Could we generalize that check to look for all location-based events? For example:

1. Pacman eating dots
2. Pacman eating a powerpill
3. Pacman eating a ghost (if powerpill is enabled)
4. Ghost eating Pacman

I don't think we've confirmed if distance is the best way to check if a ghost has eaten Pacman ( or vice versa), but if we have the option to add it in here easily later, that would be preferred I think.

**Comment by jleung51** [comment]
For 1 + 2, definitely - a powerpill will be a type of dot (likely signified by a boolean flag).

For 3 + 4, we briefly discussed whether it would be better to have players confirm on the app that the tagging has happened, because this would solve disconnects and lag issues. Thoughts? @CtrlShiftGo

**Comment by CtrlShiftGo** [comment]
Having a check on whether the players are close to each other when the eating event occurs would be a good idea. I still think some degree of user action should be necessary when one player eats another. There's too much inaccuracy in the GPS location for our tagging to be solely based, and if it were based on proximity it removes some of the actual tagging that goes on.

That being said, I think a player should only be able to eat another when they're within some distance of the others if that's not too much trouble.

**Comment by Aarjente** [comment]
Confirmation that a tag has happened sounds like the best way to go forward, as like you guys mentioned the inaccuracy is an issue - if Pacman and a ghost are on opposite sides of a street it would probably be difficult to check that. 

Adding a proximity check to allow for the player to send confirmation makes sense, - the other option is to have both clients involved in the tag affirm.

**Comment by jleung51** [comment]
The way I see it, if the players have to physically tag, then they have to have at least one person confirm through the phone. From there, it's not a big change to have both players confirming on their phones - which no longer requires proximity checking.

**Comment by jleung51** [comment]
Proposed API documentation:

# API Documentation for Pacdots

## Get All Pacdots

### Description
Retrieves the locations of all Pacdots, whether they have been eaten, and whether they are a Powerdot.

### Request

#### Method
`GET`

#### Mapping

`/pacdots`

### Response

#### Codes
| HTTP Status Code | Meanings |
| --- | --- |
| `200 OK` | Retrieved all Pacdots succesfully |
| `500 Internal Server Error` | An error occurred which could not be resolved |

#### JSON body
```
[
	{
		"location" : {
			"latitude" : 999.999,
			"longitude" : 888.888
		},
		"eaten" : true,
		"powerdot" : false
	},
	{
		"location" : {
			"latitude" : 999.999,
			"longitude" : 888.888
		},
		"eaten" : false,
		"powerdot" : true
	}
]
```

[Example cURL call](https://github.com/pacmacro/pm-server/blob/master/api-calls/pacdots/get_all_pacdots.sh)

**Comment by jleung51** [comment]
Controller added in [this merge](https://github.com/pacmacro/pm-server/commit/04ed84d1f4320a112af6f79002f725d59d2240ab). I have added the documentation to the wiki.

@pacmacro/android @pacmacro/ios 
You can now use this controller to retrieve the Pacdot locations; they are currently hardcoded so we'll need to choose coordinates for them in the future.

Only sanity tests [have been written](https://github.com/pacmacro/pm-server/commit/05daada26a94c9f3219d0daae370cb9a1ec5b58e); issue #47 has been raised to address more comprehensive testing.
