### ISSUE TITLE
Longitude in path is truncated to integer

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-server#30]
From one of the unit tests (logs can be found [here](https://travis-ci.org/pacmacro/pm-server/builds/143652411)), it is clear that the digits after the decimal are truncated when a decimal is passed in the HTTP path:

```
...
00:24:54.242 [main] DEBUG org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Looking up handler method for path /ghost/95837.39821/12345.54321
00:24:54.252 [main] DEBUG org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Returning handler method [public com.pm.server.response.IdResponse com.pm.server.controller.GhostController.createGhost(double,double,javax.servlet.http.HttpServletResponse) throws com.pm.server.exceptionhttp.ConflictException]
00:24:54.272 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'ghostController'
00:24:54.294 [main] DEBUG com.pm.server.controller.GhostController - Mapped POST /ghost/95837.39821/12345.0
...
```

My guess is that this is because the longitude is the last value in the path, and so the digits after the period are treated as a file extension or something similar.

To fix this, the Pacman and Ghost `createPlayer` and `setPlayerLocation` mappings should no longer have the coordinates in the path, but rather in the request body. This requires a change to the API, but is absolutely necessary.

**Comment by jleung51** [comment]
Working on this on the branch `remove-path-decimals`.

**Comment by CtrlShiftGo** [comment]
Issue addressed with [merge request 31](https://github.com/pacmacro/pm-server/pull/31).

**Comment by jleung51** [comment]
Thank you. API documentation has been updated accordingly.
