### ISSUE TITLE
Create GameState controller

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-server#34]
This will return one option from a set list, representing the current game state.

**Comment by jleung51** [comment]
When this is implemented, method `activatePowerup()` from class `PlayerRegistryImpl` should have an extra check to only reset the Pacman's state to `ACTIVE` if the gamestate is also `ACTIVE`.

**Comment by jleung51** [comment]
Proposed documentation:

# States

## Game

The game's state can be any of the following:

* INITIALIZING (Default)
* IN_PROGRESS
* PAUSED
* FINISHED_PACMAN_WIN
* FINISHED_GHOSTS_WIN

# API Documentation for Game State

## Get Current State

### Description
Returns the current state of the game.

See the [possible game states](https://github.com/pacmacro/pm-server/wiki/States).

### Request

#### Method
`GET`

#### Mapping
`/gamestate`

#### Headers

| Field | Value(s) |
| --- | --- |
| Content-Type | application/json |

### Response

#### Codes
| HTTP Status Code | Meanings |
| --- | --- |
| `200 OK` | Retrieved game state successfully |
| `500 Internal Server Error` | The server crapped itself |

#### JSON body
```
{
	"state" : "INITIALIZING"
}
```

[Example cURL call](https://github.com/pacmacro/pm-server/blob/master/api-calls/gamestate/get_current_state.sh)

**Comment by jleung51** [comment]
As I write this API documentation, I am realizing that I am not sure how we should "reset" the game after a win, during real gameplay - i.e. whether the request should be manually sent from a computer/phone, whether it should be triggered after a period of time after the game ends.

I am also unsure about how to start the game (and whether we should decide to have all 5 teams to ready-up to start the game).

For setting Pacman and Ghosts as the winners, I will likely have them be triggered by tagging events, and move these two endpoints to the Administration controller.

---

@pacmacro/android and @pacmacro/ios, please let me know your thoughts on this issue. The simplest way is to have the game administrators (likely me) using the scripts to manually trigger game state changes, but this is far from ideal.

**Comment by landalex** [comment]
I agree with manually resetting the game after it ends. For the time being, using scripts is probably the most realistic, but adding a couple buttons to the Android app won't be difficult. The hardest part is figuring out how to integrate admin functions into the app in such a way that only we can access them (which we discussed a little bit on the weekend). Maybe a hidden button? In the future, probably having people log in so we can create some kind of token will be the best approach. If this is the option we want to pursue, we can ignore the next two things that automatically change game state.

Having every player ready up sounds like a good idea to me. It could be as simple as sending a request to `ready/{player_name}`, which will be quick to integrate.

Ending the game based on a trigger within the tagging endpoint sounds good.

**Comment by jleung51** [comment]
A password-locked administrator panel or a separate (private) app could provide administrative endpoints.

I think for now, it'd be easiest and simplest to have the player selection be the ready-up, just so we don't have extend functionality further in the time that we have. We can definitely add a ready-up endpoint in the future though when we have more time.

**Comment by jleung51** [comment]
@pacmacro/android | @pacmacro/ios 

The funtionality and API endpoints have been added, and the new documentation has been added to the wiki. Please take note of the new restraints on eating Pacdots when a game is not in progress.

I warn you of using the `PAUSED` gamestate, as it has not been comprehensively tested and may not cause the game to function as intended in some minor use cases (such as pausing when the Pacman is in the `POWERUP` state).
