### ISSUE TITLE
Choose Pacdot locations

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-server#50]
The Pacdot coordinates will be hardcoded into the server, so we'll need to determine a set game area on the map and then choose Pacdot locations from there.

@pacmacro/android @pacmacro/ios @farzin94
Thoughts?

---

Some suggestions:

| Latitude | Longitude | Intersection |
| --- | --- | --- |
| 49.285315 | -123.111891 | Cordova and Seymour |
| 49.284671 | -123.110913 | Cordova and Richards |
| 49.284680 | -123.112891 | Hastings and Seymour |
| 49.284030 | -123.111913 | Hastings and Richards |

**Comment by landalex** [comment]
I recall there being a much larger area used to play the game, but I can't remember what the street boundaries were. @farzin94 do you know? We should spread the power pills out around the playable game area once we figure out the boundaries.

Also, once we know what the playable game area is, we could hard code lots of small dots for Pacman to eat. It will be tedious, but I haven't found a good way of finding coordinates in a line, so it might be necessary.

**Comment by PaulWAllan** [comment]
Hello, 
As I posted in the slacks, these are the co-ordinates we usually go with:
The middle coordinate is usually Granville + Dunsmuir, where the overhead walkway is. The boundaries are  generally Hastings on the North, Robson on the South, Hornby on the West, Richards on the East.
Please let me know thoughts on this. We could always change these up at your convenience.

**Comment by jleung51** [comment]
![Visualization](http://i.imgur.com/Vrk8VTb.png)

Personally I think these sound quite reasonable.

Do we usually place a coordinate at each intersection?

**Comment by PaulWAllan** [comment]
To save the trouble, the co-ordinates are:
| Latitude | Longitude | Intersection |
| --------- | ----------- | --------------|
| 49.286572 | -123.115857 | Hastings and Hornby |
| 49.282620 | -123.121857 | Robson and Hornby |
| 49.284032 | -123.111905 | Hastings and Richards |
| 49.280130 | -123.117864 | Robson and Richards |

Yes, we usually put a coordinate at each intersection

**Comment by jleung51** [comment]
Where are the powerdots located? I'm guessing 5 in total (one in the middle and one at each corner)?

**Comment by PaulWAllan** [comment]
Sorry for the late response.
Yeah, one in each corner works and one in the middle works.

**Comment by jleung51** [comment]
List of the 25 coordinates I am adding:

| Latitude | Longitude | Intersection | Powerdot? |
| --- | --- | --- | --- |
| 49.280098 | -123.117852 | Robson and Richards | Yes (South) |
| 49.280738 | -123.118839 | Robson and Seymour | No |
| 49.281223 | -123.116168 | Georgia and Richards | No |
| 49.281370 | -123.119825 | Robson and Granville | No |
| 49.281856 | -123.117134 | Georgia and Seymour | No |
| 49.282009 | -123.120824 | Robson and Howe | No |
| 49.282365 | -123.114479 | Dunsmuir and Richards | No |
| 49.282498 | -123.118105 | Georgia and Granville | No |
| 49.282639 | -123.121772 | Robson and Hornby | Yes (West) |
| 49.282998 | -123.115417 | Dunsmuir and Seymour | No |
| 49.283157 | -123.119148 | Georgia and Howe | No |
| 49.283387 | -123.112884 | Pender and Richards | No |
| 49.283609 | -123.116464 | Dunsmuir and Granville | Yes (Center) |
| 49.283773 | -123.120101 | Georgia and Hornby | No |
| 49.284027 | -123.113871 | Pender and Seymour | No |
| 49.284038 | -123.111918 | Hastings and Richards | Yes (East) |
| 49.284273 | -123.117438 | Dunsmuir and Howe | No |
| 49.284671 | -123.112873 | Hastings and Seymour | No |
| 49.284673 | -123.114868 | Pender and Granville | No |
| 49.284896 | -123.118388 | Dunsmuir and Hornby | No |
| 49.285297 | -123.115855 | Pender and Howe | No |
| 49.285308 | -123.113863 | Hastings and Granville | No |
| 49.285931 | -123.116808 | Pender and Hornby | No |
| 49.285948 | -123.114857 | Hastings and Howe | No |
| 49.286575 | -123.115834 | Hastings and Hornby | Yes (North) |

I will add these to the wiki once I have added the coordinates to the code.

**Comment by jleung51** [comment]
Completed in the above-referenced commit.

The coordinates have been [added](https://github.com/pacmacro/pm-server/wiki/Pacdot-Locations) to the wiki.

@pacmacro/android, when you have the ability to see the Pacdots and Powerdots on the map, please confirm and let me know whether they are all in the correct locations.
