### ISSUE TITLE
Delay disappearance of Pacdots after being eaten

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-server#62]
# Tentative Proposal

### Current Implementation

Pacdots disappear immediately when they are eaten.

### Proposed Implementation

Pacdots disappear a short delay after they are eaten (5-15 seconds).

### Benefits

The Pacman's current location is obfuscated.

### Drawbacks

The current game state is obfuscated for the players, as all the Pacdots may be eaten unexpectedly.

**Comment by jleung51** [comment]
I think this may be too confusing for the players, as it is not easily obvious that the disappearance of the Pacdots is delayed.

@pacmacro/android, thoughts?

**Comment by landalex** [comment]
I agree it's too confusing, I think the current implementation is alright as it is. This mechanic in particular is working well.
